run:
  timeout: 60s
  tests: false

linters-settings:
  errcheck:
    check-type-assertions: true
  gosimple:
    checks: ["all"]
  staticcheck:
    checks: ["all"]

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  formats:
    - format: colored-line-number
